/*
 * LoginFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.megalight.view;

//import org.apache.log4j.Logger;

import java.awt.Font;
import java.awt.event.KeyEvent;

import org.apache.log4j.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

import com.megalight.dao.UserDao;
import com.megalight.model.User;
import com.megalight.util.StringUtil;

/**
 * 
 * @author __USER__
 */
public class LoginFrm extends javax.swing.JFrame {
	/**
	 * Logger for this class
	 */
	private static final Logger logger = Logger.getLogger(LoginFrm.class);

	private UserDao userDao = new UserDao();

	/** Creates new form LoginFrm */
	public LoginFrm() {
		// 改变系统默认字体
		Font font = new Font("Dialog", Font.PLAIN, 15);
		java.util.Enumeration keys = UIManager.getDefaults().keys();
		while (keys.hasMoreElements()) {
			Object key = keys.nextElement();
			Object value = UIManager.get(key);
			if (value instanceof javax.swing.plaf.FontUIResource) {
				UIManager.put(key, font);
			}
		}

		initComponents();
		// 位置居中  壹 贰 叁
		this.setLocationRelativeTo(null);
//		JOptionPane.showMessageDialog(this, "叁叁叁叁叁叁叁叁叁叁叁");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		userNameTxt = new javax.swing.JTextField();
		jb_login = new javax.swing.JButton();
		jb_quit = new javax.swing.JButton();
		userPWTxt = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u7528\u6237\u767b\u5f55");
		setResizable(false);

		jLabel1.setFont(new java.awt.Font("新宋体", 0, 24));
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/logo.png"))); // NOI18N
		jLabel1.setText("\u5f55\u50cf\u4e0a\u4f20\u7cfb\u7edf");

		jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel2.setText("\u7528 \u6237");

		jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel3.setText("\u5bc6 \u7801");

		userNameTxt.setFont(new java.awt.Font("微软雅黑", 0, 18));
		
		userNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				//回车登录
				if(evt.getKeyCode() == KeyEvent.VK_ENTER){
					login();
				}
			}

			public void keyReleased(java.awt.event.KeyEvent evt) {
			}
		});

		jb_login.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jb_login.setText("\u767b\u5f55");
		jb_login.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jb_loginActionPerformed(evt);
			}
		});

		jb_quit.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jb_quit.setText("\u9000\u51fa");
		jb_quit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jb_quitActionPerformed(evt);
			}
		});

		userPWTxt.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				if(evt.getKeyCode() == KeyEvent.VK_ENTER){
					login();
				}
			}

			public void keyReleased(java.awt.event.KeyEvent evt) {
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(101, 101, 101)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(11, 11,
																		11)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jLabel2,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														41,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														jLabel3,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														49,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGap(29,
																										29,
																										29)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														userNameTxt,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														149,
																														Short.MAX_VALUE)
																												.addComponent(
																														userPWTxt,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														149,
																														Short.MAX_VALUE))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(15,
																										15,
																										15)
																								.addComponent(
																										jb_login,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										73,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																										52,
																										Short.MAX_VALUE)
																								.addComponent(
																										jb_quit)
																								.addGap(18,
																										18,
																										18))))
												.addComponent(
														jLabel1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														224,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(127, 127, 127)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(38, 38, 38)
								.addComponent(jLabel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										51,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(29, 29, 29)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														userNameTxt,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														userPWTxt,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														29,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(27, 27, 27)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jb_login,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														33,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jb_quit,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
								.addGap(68, 68, 68)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents


	// 退出按钮
	private void jb_quitActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}

	// 登录
	private void jb_loginActionPerformed(java.awt.event.ActionEvent evt) {
		login();
	}

	/**
	 * @Description: 登录方法
	 */
	private void login() {
		String userName = userNameTxt.getText().trim();
		String password = new String(userPWTxt.getPassword()).trim();

		if (StringUtil.isEmpty(userName)) {
			JOptionPane.showMessageDialog(this, "用户名不能为空");
			return;
		}

		if (StringUtil.isEmpty(password)) {
			JOptionPane.showMessageDialog(this, "密码不能为空");
			return;
		}

		try {
			User currentUser = userDao.login(userName, password);
			// JOptionPane.showMessageDialog(this, "登录成功");

			this.dispose();

			if (logger.isInfoEnabled()) {
				logger.info("loginSuccess - " + userName);
			}

			new PQXXFrm(currentUser).setVisible(true);

		} catch (Exception e) {
			if (logger.isInfoEnabled()) {
				logger.info("[user:" + userName + "]-loginfailed");
			}

			JOptionPane.showMessageDialog(this, e.getMessage());
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LoginFrm().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JButton jb_login;
	private javax.swing.JButton jb_quit;
	private javax.swing.JTextField userNameTxt;
	private javax.swing.JPasswordField userPWTxt;
	// End of variables declaration//GEN-END:variables

}