/*
 * PQXXFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.megalight.view;

//import org.apache.log4j.Logger;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;

import com.megalight.dao.CourtDao;
import com.megalight.dao.PQInfoDao;
import com.megalight.model.Court;
import com.megalight.model.PQKTInfo;
import com.megalight.model.User;
import com.megalight.util.IPUtil;

/**
 * 
 * @author __USER__
 */
public class PQXXFrm extends javax.swing.JFrame {
//	/**
//	 * Logger for this class
//	 */
//	private static final Logger logger = Logger.getLogger(PQXXFrm.class);

	private PQInfoDao pqInfoDao = new PQInfoDao();
	private CourtDao courtDao = new CourtDao();
	private User user;
	private Court court;

	/**
	 * @return the court
	 */
	public Court getCourt() {
		return court;
	}

	/**
	 * @param court
	 *            the court to set
	 */
	public void setCourt(Court court) {
		this.court = court;
	}

	private PQKTInfo info = new PQKTInfo();

	List<PQKTInfo> infoList = new ArrayList<PQKTInfo>();

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	/** Creates new form PQXXFrm */
	public PQXXFrm(User user) {
		// 改变系统默认字体
		Font font = new Font("Dialog", Font.PLAIN, 13);
		java.util.Enumeration keys = UIManager.getDefaults().keys();
		while (keys.hasMoreElements()) {
			Object key = keys.nextElement();
			Object value = UIManager.get(key);
			if (value instanceof javax.swing.plaf.FontUIResource) {
				UIManager.put(key, font);
			}
		}

		this.user = user;
		// 初始化控件
		initComponents();

		// 查询法庭信息
		try {
			court = courtDao.findCourtByIP(IPUtil.getIP());
			// 11号庭 149.70.211.111
			//court = courtDao.findCourtByIP("149.70.211.111");
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, e.getMessage());
//			if (logger.isInfoEnabled()) {
//				logger.info("PQXXFrm" + e.getMessage());
//			}
		}

		// 控件初始化值
		fillData();

		// 位置居中
		this.setLocationRelativeTo(null);

	}

	/**
	 * @Description: 年度号 本年 ，table初始化
	 */
	private void fillData() {
		// 对齐方式、列高宽
		setAlign(jtablePqxx);
		setColumnWidth(jtablePqxx);

		DateFormatter df = new DateFormatter(new SimpleDateFormat("yyyy"));
		jftNdh.setFormatterFactory(new DefaultFormatterFactory(df));
		jftNdh.setValue(new Date());

		search();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 * 
	 * @throws ParseException
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jtfAjbh = new javax.swing.JTextField();
		jcb = new javax.swing.JComboBox();
		jLabel3 = new javax.swing.JLabel();
		jb_search = new javax.swing.JButton();
		jftNdh = new javax.swing.JFormattedTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		jtablePqxx = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("\u6392\u671f\u4fe1\u606f\u5217\u8868");
		setMinimumSize(new java.awt.Dimension(20, 20));
		setResizable(false);

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(
				javax.swing.BorderFactory.createLineBorder(new java.awt.Color(
						0, 0, 0)), "\u67e5\u8be2\u6392\u671f\u4fe1\u606f",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("微软雅黑", 0, 14)));

		jLabel1.setText("\u5e74\u5ea6\u53f7");

		jLabel2.setText("\u6848\u4ef6\u7f16\u53f7");

		jcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "未回传",
				"已回传" }));

		jLabel3.setText("\u72b6\u6001");

		jb_search.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/search.png"))); // NOI18N
		jb_search.setText("\u67e5\u8be2");
		jb_search.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jb_searchActionPerformed(evt);
			}
		});
		jcb.addItemListener(new ItemListener() {
			public void itemStateChanged(ItemEvent e) {
				if (e.getStateChange() == ItemEvent.SELECTED) {
					search();
				}
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(83, 83, 83)
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jftNdh,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												75,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(41, 41, 41)
										.addComponent(jLabel2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jtfAjbh,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												91,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(31, 31, 31)
										.addComponent(
												jLabel3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												35,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jcb,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(76, 76, 76)
										.addComponent(jb_search)
										.addContainerGap(124, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.CENTER)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																38,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jb_search,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																34,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jftNdh,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																32,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jtfAjbh,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																32,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jcb,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(29, Short.MAX_VALUE)));

		jtablePqxx.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null },
						{ null, null, null, null, null, null },
						{ null, null, null, null, null, null },
						{ null, null, null, null, null, null },
						{ null, null, null, null, null, null },
						{ null, null, null, null, null, null } }, new String[] {
						"案号全称", "立案理由", "原告", "被告", "开庭序号", "开庭日期" }) {
			Class[] types = new Class[] { java.lang.String.class,
					java.lang.String.class, java.lang.String.class,
					java.lang.String.class, java.lang.String.class,
					java.lang.String.class };
			boolean[] canEdit = new boolean[] { false, false, false, false,
					false, false };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jtablePqxx.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jtablePqxxMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(jtablePqxx);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(39, 39, 39)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												false)
												.addComponent(
														jPanel1,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														806, Short.MAX_VALUE))
								.addContainerGap(36, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										20, Short.MAX_VALUE)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										403,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	// 设置表格列宽
	private void setColumnWidth(JTable table) {
		// 行高
		table.setRowHeight(20);

		TableColumnModel columnModel = table.getColumnModel();
		// 零列隐藏
		// TableColumn column0 = columnModel.getColumn(0);
		// column0.setPreferredWidth(0);
		// column0.setMaxWidth(0);
		// column0.setMinWidth(0);
		// column0.setWidth(0);
		columnModel.getColumn(0).setPreferredWidth(120);
		columnModel.getColumn(1).setPreferredWidth(80);
		columnModel.getColumn(2).setPreferredWidth(120);
		// 原告
		columnModel.getColumn(3).setPreferredWidth(80);
		columnModel.getColumn(4).setPreferredWidth(10);
		columnModel.getColumn(5).setPreferredWidth(50);
	}

	// 表格设置为水平居中对齐
	private void setAlign(JTable table) {
		// 设置对齐方式
		DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
		renderer.setHorizontalAlignment(JLabel.CENTER);
		TableColumnModel columnModel = table.getColumnModel();

		for (int i = 0; i < table.getColumnCount(); i++) {
			columnModel.getColumn(i).setCellRenderer(renderer);
		}
	}

	private void jtablePqxxMouseClicked(java.awt.event.MouseEvent evt) {
		// 双击处理,隐藏该窗体、打开开庭信息
		if (evt.getClickCount() == 2) {
			// 获取选中的行
			int row = this.jtablePqxx.getSelectedRow();
			info = infoList.get(row);
			// 更新 开庭日期，笔录名称  + lxurl
			PQKTInfo updated = null;
			try {
				updated = pqInfoDao.findPQKTInfo(//
						info.getNdh(), info.getAjbh(), info.getXh());
			} catch (Exception e) {
				e.printStackTrace();
			}
			if (updated != null) {
				info.setKtrq(updated.getKtrq());
				info.setBlmc(updated.getBlmc());
				info.setLxurl(updated.getLxurl());
			}
			this.setVisible(false);
			new KTInfoFrm(info, this).setVisible(true);
		}
	}

	// 搜索按钮
	protected void jb_searchActionPerformed(ActionEvent evt) {
		search();
	}

	/**
	 * @Description: 搜索 开庭信息
	 */
	private void search() {
		Boolean updated = Boolean.FALSE;// 未回传
		// 这必须是数字
		Object ndhObject = jftNdh.getValue();
		if (ndhObject == null) {
			JOptionPane.showMessageDialog(this, "年度号为4位数字，不能为空");
			// 控件获得焦点
			SwingUtilities.invokeLater(new Runnable() {
				public void run() {
					jftNdh.requestFocusInWindow();
				}
			});
			return;
		}
		Integer ndh = Integer.parseInt(jftNdh.getText());
		if ("已回传".equals((String) jcb.getSelectedItem())) {
			updated = Boolean.TRUE;
		}

		// 案件编号可为空
		String ajbh = jtfAjbh.getText().trim();
		String sjydm = this.user.getUserCode().trim();
		// 获得表格的Model
		DefaultTableModel model = (DefaultTableModel) jtablePqxx.getModel();
		model.setRowCount(0);// 清空表格

		infoList = new ArrayList<PQKTInfo>();
		try {
			infoList = pqInfoDao.listCases(ndh, ajbh, sjydm, updated);
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, "网络或服务器故障，请联系管理员");
		}
		if (infoList == null || infoList.size() == 0) {
			JOptionPane.showMessageDialog(this, "没有记录");
		} else {
			// 数据填充表格
			for (PQKTInfo info : infoList) {
				if (court != null) {// 找到法庭
					info.setFtbm(court.getFtbm());
					info.setFtmc(court.getFtmc());
				}

				Vector v = new Vector();
				// v.add(info.getNdh());
				// v.add(info.getAjbh());
				v.add(info.getAhqc());// 案号全称
				v.add(info.getLaayname());
				v.add(info.getDyyg());
				v.add(info.getDybg());
				v.add(info.getXh());
				v.add(info.getKtrq().toString());
				model.addRow(v);
			}
		}
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JButton jb_search;
	private javax.swing.JComboBox jcb;
	private javax.swing.JFormattedTextField jftNdh;
	private javax.swing.JTable jtablePqxx;
	private javax.swing.JTextField jtfAjbh;
	// End of variables declaration//GEN-END:variables

}